name: "laundry_customer"
description: A new Flutter project.

publish_to: "none"

version: 1.0.4+12

environment:
   sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #Design
  flutter_screenutil: ^5.5.3+2
  #State management
  flutter_riverpod: ^2.4.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  circle_nav_bar: ^2.0.1
  dotted_line_flutter: ^2.1.8

  #Api Handling
  dio: ^5.3.3
  pretty_dio_logger: ^1.2.0-beta-1
  freezed_annotation: ^3.0.0
  font_awesome_flutter: ^10.7.0
  #Form
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.0.0

  smooth_page_indicator: ^1.1.0
  #Local DataBase
  hive_flutter: ^1.1.0
  #Routing
  page_transition: ^2.0.9
  #Misc
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  carousel_slider: ^5.0.0
  logger: ^2.0.2+1
  pin_code_fields: ^8.0.1
  animated_bottom_navigation_bar: ^1.0.0
  expandable: ^5.0.1
  
  flutter_rating_bar: ^4.0.1
  collection: ^1.16.0
  image_picker: ^1.0.4
  flutter_html: ^3.0.0-alpha.5
  table_calendar: ^3.0.6
  url_launcher: ^6.1.5
  upgrader: ^11.0.0
  # flutter_launch: ^0.3.0
  cached_network_image: ^3.2.3
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  # change_app_package_name: ^1.1.0
  socket_io_client: ^3.1.2
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  google_nav_bar: ^5.0.7                           
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^3.0.6
  lint: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
   
        

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/log.png'


  remove_alpha_ios: true
